# Generated by Django 2.2.2 on 2019-06-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Railjets',
            fields=[
                ('train_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='obb.Train')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('obb.train', models.Model),
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.ManyToManyField(blank=True, to='obb.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=-1)),
                ('person', models.ManyToManyField(blank=True, to='obb.Person')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='train_section',
            field=models.ManyToManyField(blank=True, to='obb.TrainSection'),
        ),
        migrations.AddField(
            model_name='platform',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obb.Train'),
        ),
        migrations.CreateModel(
            name='ICE',
            fields=[
                ('train_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='obb.Train')),
                ('name', models.CharField(max_length=100)),
                ('train', models.ManyToManyField(blank=True, related_name='_ice_train_+', to='obb.ICE')),
            ],
            bases=('obb.train', models.Model),
        ),
    ]
